<a href="https://colab.research.google.com/github/jonnathanZsicha/Simtraffic/blob/master/PruebaSimulacionV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalacion de Librerias necesarias

In [374]:
import panel as pn
pn.extension('plotly')
import altair as alt
import pandas as pd
from vega_datasets import data
import datetime as dt
from altair import datum
from pandas import read_csv
from datetime import datetime
import pandas as pd
from matplotlib import pyplot
import numpy as np
from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.models import model_from_json
from sklearn.metrics import mean_squared_error
from keras.layers import Dense,Activation,Flatten
!pip install --upgrade plotly
import datetime
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
!datapane hello-world
!pip3 install -U datapane

Creating and running `./hello.py` - running this code generates a sample Datapane report. You can edit the script and run it again to change the generated report.

[20:11:14] [WARNING] Bokeh version 2.3.3 is not supported, these plots may not display correctly, please install version ~=2.2.0
[20:11:14] [WARNING] Folium version 0.8.3 is not supported, these plots may not display correctly, please install version >=0.12.0
Report saved to ./hello.html. To upload and share your report, create a free Datapane account by running `datapane signup`.

Next, run `datapane signup` to create a free account and upload a report.


Lectura de Dataset sectorizacion

In [375]:
#LOADING DATA Sectorizacion
dfSectorizacion= pd.read_csv('/content/4. Sectorización del empleo.csv', error_bad_lines=False ,sep=';' , encoding='latin-1' ) 
dfSectorizacion.tail(5)

Característica                  Unnamed: 1 jun-07  ...  ago-21  sep-21  oct-21
7             NaN  No Clasificados por Sector  4,40%  ...   5,30%   4,80%   4,40%
8           Rural               Sector Formal      -  ...  21,00%  24,90%  20,40%
9             NaN             Sector Informal      -  ...  71,20%  69,90%  74,80%
10            NaN            Empleo Doméstico      -  ...   1,00%   1,30%   0,90%
11            NaN  No Clasificados por Sector      -  ...   6,70%   3,90%   3,90%

[5 rows x 67 columns]

##Descripcion de Variables del dataset Sectorizacion
-Característica : tipo Categorico refecte al sector:


*   urbano
*   Rural , Nacional


-Sector : Tipo Categorico de los diferentes sectores de empleo

-jun-07 y las demas columnas son de tipo Float indicando el porcentaje de empleo en cada fecha

Preprocesamiento dataset

In [376]:
dfSectorizacion.iloc[1:4].fillna("Nacional", inplace = True) 
dfSectorizacion.iloc[1:9].fillna("Urbano", inplace = True) 
dfSectorizacion.iloc[1:].fillna("Rural", inplace = True)
df=dfSectorizacion.replace('\%','',regex=True)
df=df.replace('\-','0',regex=True)
df=df.replace('\,','.',regex=True)
df.rename(columns={'Unnamed: 1':'Sector'}, inplace=True)
df=df.drop(columns=df.columns[(df == '0').any()])
df1=df[['Característica','Sector']]
df2=df.iloc[:,2:].apply(pd.to_numeric)
df=pd.concat([df1, df2], axis=1)
df.head(5)


/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



Característica                      Sector  dic-07  ...  ago-21  sep-21  oct-21
0       Nacional               Sector Formal    41.0  ...    41.2    43.9    41.4
1       Nacional             Sector Informal    45.1  ...    50.6    49.2    52.2
2       Nacional            Empleo Doméstico     3.3  ...     2.4     2.4     2.2
3       Nacional  No Clasificados por Sector    10.6  ...     5.8     4.5     4.2
4         Urbano               Sector Formal    54.1  ...    52.1    54.3    52.5

[5 rows x 52 columns]

In [377]:
import plotly.express as px
import datapane as dp
# set a title for your dashboard
title = 'Porcentaje de Empleo por sectorizacion'

subtitle = 'Seleccionar Periodo de fecha en la que quiere el grafico de pie'

# create list of company names (tickers)
tickers = opciones

# this creates the dropdown widget
ticker = pn.widgets.Select(name='Select', options=[ 'dic-07', 'jun-08', 'dic-08', 'dic-09',
       'jun-10', 'dic-10', 'jun-11', 'dic-11', 'jun-12', 'dic-12', 'jun-13',
       'dic-13', 'mar-14', 'jun-14', 'sep-14', 'dic-14', 'mar-15', 'jun-15',
       'sep-15', 'dic-15', 'mar-16', 'jun-16', 'sep-16', 'dic-16', 'mar-17',
       'jun-17', 'sep-17', 'dic-17', 'mar-18', 'jun-18', 'sep-18', 'dic-18',
       'mar-19', 'jun-19', 'sep-19', 'dic-19', 'sep-20', 'oct-20', 'nov-20',
       'dic-20', 'ene-21', 'feb-21', 'mar-21', 'abr-21', 'may-21', 'jun-21',
       'jul-21', 'ago-21', 'sep-21', 'oct-21'])

# tell Panel what your plot "depends" on. 
# This defines what should trigger a change in the chart.
# both values in depends() will be used in our below Altair chart as filters
@pn.depends(ticker.param.value)
def get_plot(ticker): # start function

     # create the Altair chart object
    import plotly.express as px
    fig = px.sunburst(df, path=["Característica","Sector"], values=df[ticker])
    fig.update_layout( margin = dict(t=10, l=10, r=10, b=10),colorway=("#FF3371","#FFD433","#33FFA2",'#3386FF','#FF33C1'))

    fig.update_layout(title='<b>Grafico % sectorización de empleo</b>',title_font_size=25,
                  margin = dict(t=100, l=100, r=50, b=100),
                  height=700, width=700)
    fig.update_traces(hovertemplate='<b>ID</b>: %{id}<br>'+
                                '<b>Personas%</b>: %{value}%<br>'+
                                '<b>Sector</b>: %{parent}') 
    fig.add_annotation(dict(font=dict(size=14),
                                    x=0.8,
                                    y=-0.2,
                                    showarrow=False,
                                    text="@green_yhjw",
                                    xanchor='left',
                                    xref="paper",
                                    yref="paper"))
    dp.Report(
    dp.Text("sectorizacion de personas "),
    dp.Plot(fig),
    dp.DataTable(df)
    ).save(path="sectorizacion.html")
    return fig

In [378]:
# create the Panel object, passing in all smaller objects
dashboard = pn.Row(
    pn.Column(title, subtitle, ticker),
    get_plot # draw chart function!
)

Report saved to ./sectorizacion.html. To upload and share your report, create a free Datapane account by running `datapane signup`.


In [379]:
dashboard.servable()

Row
    [0] Column
        [0] Markdown(str)
        [1] Markdown(str)
        [2] Select(options=['dic-07', 'jun-08', ...], value='dic-07')
    [1] ParamFunction(function)

#Conclusion
Con el presente grafico podemos observar que desde el 2007 a nivel nacional el porcentaje de empleo en el sector formal es de 54.1% a diferencia de hoy en la actualidad este ha cambiado a la fecha octubre 2021 el porcentaje formal a decaido a un 41.4% subiendo de porcentaje el sector informal.

In [380]:
# Import plotly and create a figure
import plotly.graph_objects as go
fig = go.Figure()



# Add the bar chart traces to the graph
for column_header in ['oct-21', 'dic-07']:
    fig.add_trace(
        go.Bar( 
            x=df['Sector'],
            y=df[column_header],
            name=str(column_header)
        )
    )

# Update the title and stacking mode of the graph

fig.update_layout(
    xaxis_title="Comparacion por Sector fechas",
    yaxis_title="",
    title="Sectorizacion, oct-21, jun-07 bar chart",
    barmode='group',
)
dp.Report(
    dp.Text("sectorizacion de personas "),
    dp.Plot(fig),
    dp.DataTable(df)
    ).save(path="Comparacion por Sector fechas")
fig.show()

Report saved to ./Comparacion por Sector fechas. To upload and share your report, create a free Datapane account by running `datapane signup`.


Lectura de Datos del Dataset Poblacion

In [381]:
#LOADING DATA Poblacion
dfp= pd.read_csv('/content/1.Poblaciones.csv', error_bad_lines=False ,sep=';' , encoding='latin-1' ) 
dfp.head(5)

Encuesta Periodo  ...       Sexo Unnamed: 7
0      NaN     NaN  ...     Hombre      Mujer
1   ENEMDU  dic-07  ...  6.768.646  6.913.656
2   ENEMDU  dic-07  ...  2.226.618  2.146.194
3   ENEMDU  dic-07  ...  4.542.028  4.767.462
4   ENEMDU  dic-07  ...  3.777.232  2.558.798

[5 rows x 8 columns]

Descripcion de Variable dataset Poblacion

-Encuesta : nombre de la Encuesta

-Periodo : tipo Date Fecha del periodo realizado la encuesta

-Indicadores :Tipo de trabajo que realiza cierta poblacion

-Nacional : tipo Float total de la poblacion a nivel nacional

-Urbanna y Rural : Area donde se encuentra la poblacion

-Hombre y mujer : el porcentaje tanto en hombres y mujeres dentro del area  


In [383]:
# Import plotly and create a figure
import plotly.graph_objects as go
fig = go.Figure()



# Add the scatter traces to the figure
for column_header in ['Periodo']:
    fig.add_trace(go.Scatter(
        x=dfp[column_header],
        y=dfp['Nacional'],
        mode='markers',
        name=str(column_header)
    ))

# Update the layout

fig.update_layout(
    xaxis_title="Periodo",
    yaxis_title="Poblacion",
    title="Evolucion Empleo, Nacional segun las fechas",
)

fig.show()

Preprocesamiento Dataset

In [384]:
dfp.rename(columns={'Área':'Urbana','Unnamed: 5':'Rural','Sexo':'Hombre','Unnamed: 7':'Mujer'}, inplace=True)
dfp=dfp.drop([0],axis=0)

In [385]:
meses={"ene":"jan","feb":"feb","mar":"mar","abr":"apr","may":"may","jun":"jun","jul":"jul","ago":"aug","sep":"sep","oct":"oct","nov":"nov","dic":"dec"}
for i in range(len(dfp)):
  month_name=str(dfp.Periodo.iloc[i]).split('-')[0]
  month_name= meses.get(month_name)
  datetime_object = datetime.datetime.strptime(month_name, "%b")
  month_number = datetime_object.month
  year=str(dfp.Periodo.iloc[i]).split('-')[1]
  date_formated=("20"+str(year)+"-"+str(month_number)+"-01")
  dfp.Periodo.iloc[i]=date_formated

Agrupacion por Subempleo

In [386]:
df=dfp.loc[dfp['Indicadores'].isin(['Subempleo'])]
df=df[['Periodo','Nacional',	'Urbana',	'Rural',	'Hombre',	'Mujer']]
dfp1=df['Periodo']
df=df.replace('\.','',regex=True)
dfp2=df.iloc[:,1:].apply(pd.to_numeric)
df=pd.concat([dfp1, dfp2], axis=1)
df.tail(5)

Periodo  Nacional   Urbana   Rural   Hombre   Mujer
817   2021-6-01   1917390  1310574  606816  1205167  712224
835   2021-7-01   2035106  1389069  646037  1255730  779376
853   2021-8-01   1887050  1221012  666038  1223683  663367
871   2021-9-01   1921312  1170752  750560  1159844  761468
889  2021-10-01   2005393  1269913  735480  1212008  793384

In [388]:
fig = px.histogram(df, x="Periodo", y="Nacional", histfunc="avg", title="Histograma Subempleo Nacional")
fig.update_traces(xbins_size="M1")
fig.update_xaxes(showgrid=True, ticklabelmode="period", dtick="M4", tickformat="%b\n%Y")
fig.update_layout(bargap=0.1)
fig.add_trace(go.Scatter(mode="markers", x=df["Periodo"], y=df["Nacional"], name="Total de Personas"))

fig.show()

Conclusion

El subempleo en octubre del 2020es el mayor comparado con los demas muestras en la poblacion.

In [391]:

df=dfp.loc[dfp['Indicadores'].isin(['Empleo Adecuado/Pleno'])]
df=df[['Periodo','Nacional',	'Urbana',	'Rural',	'Hombre',	'Mujer']]
dfp1=df['Periodo']
df=df.replace('\.','',regex=True)
dfp2=df.iloc[:,1:].apply(pd.to_numeric)
df=pd.concat([dfp1, dfp2], axis=1)
df.tail(5)

fig = px.histogram(df, x="Periodo", y="Nacional", histfunc="avg", title="Histograma Empleo Pleno Nacional")
fig.update_traces(xbins_size="M1")
fig.update_xaxes(showgrid=True, ticklabelmode="period", dtick="M4", tickformat="%b\n%Y")
fig.update_layout(bargap=0.1)
fig.add_trace(go.Scatter(mode="markers", x=df["Periodo"], y=df["Nacional"], name="Total de Personas"))

   
fig.show()

Conclusion 

En los ultimos meses del 2021 a la mayoria de las personas se les despio de su puesto de trabajo , por la pandemia muchos persieron su trabajo por lo que en el periodo del 2014 al 2020 la poblacion tenia una tasa de empleo pleno muy alta.

In [393]:
df=dfp.loc[dfp['Indicadores'].isin(['Otro Empleo no pleno'])]
df=df[['Periodo','Nacional',	'Urbana',	'Rural',	'Hombre',	'Mujer']]
dfp1=df['Periodo']
df=df.replace('\.','',regex=True)
dfp2=df.iloc[:,1:].apply(pd.to_numeric)
df=pd.concat([dfp1, dfp2], axis=1)
df.tail(5)

fig = px.histogram(df, x="Periodo", y="Nacional", histfunc="avg", title="Histograma No pleno Nacional")
fig.update_traces(xbins_size="M1")
fig.update_xaxes(showgrid=True, ticklabelmode="period", dtick="M4", tickformat="%b\n%Y")
fig.update_layout(bargap=0.1)
fig.add_trace(go.Scatter(mode="markers", x=df["Periodo"], y=df["Nacional"], name="Total de Personas"))

fig.show()

Conclusion 

El empleo no Pleno se puede ver que  supera el semestre 2020-2021 a todos los demas esto debido a la pandemia que estamos atravesando siendo el mes de Diciembre y Agosto del 2020 los mas altos.  

Recomendacion

Se recomienda a las personas generar mas emprendimientos en la Zona , para asi poder Generar mas empleo pleno y disminuir el grado de empleo informal que va en aumento esto debio a la pandemia Que estamos atravesando.